### ISSUE TITLE
missing information in the article

### ISSUE THREAD

**Issue by EmilAlipiev** [DanielCauser/SocialLoginSamples#10]
Hi,

thanks for your nice documentation, i would like to say that a step is missing. when you debug, you need to  sign your project with cert used to create SHA1 code, otherwise you get status as "cancelled" as some of them complained in the comments. 
![capture](https://user-images.githubusercontent.com/10422347/40844099-57dfbdee-65b3-11e8-9ccc-d61142a1c738.PNG)

Beside that it would be nice if you could extend your article how to get token which can be used for services like firebase etc. 

thank you for your help.

Emil

**Comment by DanielCauser** [comment]
THank you my friend, I will make sure to edit the blog post and add this extra information!
