### ISSUE TITLE
Not asking for continue with this user

### ISSUE THREAD

**Issue by chahidkhalil7** [DanielCauser/SocialLoginSamples#11]
I downloaded this example and try it. My problem is that it does not ask to continue with this account it automatically get the logged in account on the FB app and if I logged out from the FB app it asks to choose a user.(Is this the normal behavior?)

**Comment by EmilAlipiev** [comment]
you should learn the concept of authentication. there is no real logout action. logout is all about your application. every application you login with facebook keeps the session "always" open unless access token is expiring by facebook/google. when you use an app with facebook login and if you log out, app is just logging you out from it is app, removes cached access token from app storage, when you try to login, it will ask you choose facebook user again if it is a native implementation unless you log out from your facebook app. i hope that it is clear for you. just read some articles, there are nice written once
