### ISSUE TITLE
iOS _viewController NullReferenceException

### ISSUE THREAD

**Issue by petarkekez** [DanielCauser/SocialLoginSamples#3]
I am getting null NullReferenceException.

The exception is thrown when the method PresentViewController  is called on iOS Google manager.  
When the method is called the field _viewController is null

If you can take a look it would be great.

Thank you in advance, and a great tutorial.

**Comment by DanielCauser** [comment]
Hey, I stupidly was not assigning the instance to the class property! Thank you for reporting this issue! Please test it out and see if it is fixed now!

**Comment by petarkekez** [comment]
Still not working. It should look like this:
```
while (vc.PresentedViewController != null)
{
    vc = vc.PresentedViewController;
}

_viewController = vc;
```

**Comment by petarkekez** [comment]
i tested it like that and it works
