### ISSUE TITLE
_googleManager.Login(OnLoginComplete); error

### ISSUE THREAD

**Issue by AdamSotak** [DanielCauser/SocialLoginSamples#4]
I am getting this error when I click on the login button:
![clipboard04154](https://user-images.githubusercontent.com/33287534/35978189-54618728-0ce5-11e8-9d6c-752c23f53b42.jpg)

Unhandled Exception:

System.NullReferenceException: Object reference not set to an instance of an object.

Thank you for answers !

**Comment by DanielCauser** [comment]
Can you double check and verify that the _googleManager service is being initialized on your ViewModel construtor and also, make sure you are registering the dependency on the [MainActivity.cs](https://github.com/DanielCauser/SocialLoginSamples/blob/master/GoogleNativeLogin/GoogleNativeLogin/GoogleNativeLogin.Droid/MainActivity.cs#L34) & [AppDelegate.cs](https://github.com/DanielCauser/SocialLoginSamples/blob/master/GoogleNativeLogin/GoogleNativeLogin/GoogleNativeLogin.iOS/AppDelegate.cs#L32)

**Comment by AdamSotak** [comment]
I checked everything. Android and iOS are both initialized. What to do now ?
Thank for your answer !

**Comment by DanielCauser** [comment]
HEy @AdamSotak would it be possible for you to share your branch/fork of the project so people could take a look and bebug it?

I tested out the latest sample we have on the repo and it is working fine!

**Comment by AdamSotak** [comment]
I solved this problem. I did not enable permission and I was running the app on emulator without Google Services. Thank you for your help !

**Comment by AdamSotak** [comment]
Does this project run only as PCL ? Because I am using .NetStandard 2.0. Is this the problem ?
Thank you for your answer !

**Comment by DanielCauser** [comment]
Hmmm, this project is definitely for PCL. I need to make a new sample with net Standart. I have not checked if the packages are avaiable in standart yet.
